### ISSUE TITLE
use https for Fedora, not http

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#111]
On triannon box, rails logs read thus (with https in triannon.yml):

Faraday::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:852:in `start'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:1369:in `request'
  /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:1128:in `get'
  faraday (0.9.1) lib/faraday/adapter/net_http.rb:80:in `perform_request'
  faraday (0.9.1) lib/faraday/adapter/net_http.rb:40:in `block in call'
  faraday (0.9.1) lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
  faraday (0.9.1) lib/faraday/adapter/net_http.rb:32:in `call'
  faraday (0.9.1) lib/faraday/request/url_encoded.rb:15:in `call'
  faraday (0.9.1) lib/faraday/rack_builder.rb:139:in `build_response'
  faraday (0.9.1) lib/faraday/connection.rb:377:in `run_request'
  faraday (0.9.1) lib/faraday/connection.rb:140:in `get'
  triannon (0.5.4) app/services/triannon/ldp_loader.rb:82:in `get_ttl'

need to set ssl version stuff on faraday connection?

**Comment by ndushay** [comment]
Per Dev Ops proclamations.

**Comment by ndushay** [comment]
Tell DevOps when this is deployed.

**Comment by ndushay** [comment]
Willy thinks that puppet needs to give us an updated CA bundle:

```
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12286
* Error in TLS handshake, trying SSLv3...
> GET /fedora/rest/anno HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
```

**Comment by ndushay** [comment]
and Willy further says:

fedora box  needs a real cert, and then triannon box needs to use it

**Comment by ndushay** [comment]
waiting for SAR-2648

**Comment by ndushay** [comment]
... and fixed!  w00t!  Filing SAR ticket to tell Erin she can change puppet scripts.
