### ISSUE TITLE
Cannot delete an annotation

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/triannon#191]
This is a client console session where all the reasonable alternatives for 'id' are explored and none of them can be deleted (after creating the anno and getting it's 'id').  Do the triannon specs include a test for this?

```ruby
[12] pry(main)> r = tc.post_annotation(oa_jsonld)
=> "{\"@context\":\"http://www.w3.org/ns/oa-context-20130208.json\",\"@graph\":[{\"@id\":\"_:g70047278181060\",\"@type\":[\"dctypes:Text\",\"cnt:ContentAsText\"],\"chars\":\"I love this!\",\"format\":\"text/plain\",\"language\":\"en\"},{\"@id\":\"http://your.triannon-server.com/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f\",\"@type\":\"oa:Annotation\",\"hasBody\":\"_:g70047278181060\",\"hasTarget\":\"http://purl.stanford.edu/kq131cs7229\",\"motivatedBy\":\"oa:commenting\"}]}"
[13] pry(main)> g = tc.response2graph(r)
=> #<RDF::Graph:0x3fdadc605828(default)>
[14] pry(main)> uri = tc.annotation_uri(g)
=> #<RDF::URI:0x3fdadc779808 URI:http://your.triannon-server.com/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f>
[15] pry(main)> id = tc.annotation_id(uri)
=> "/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
[16] pry(main)> tc.delete_annotation(id)
=> false
[17] pry(main)> tc.site[id].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!`
[18] pry(main)> uri.to_s
=> "http://your.triannon-server.com/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
[19] pry(main)> tc.site[uri.to_s].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!`
[20] pry(main)> id = '/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f'
=> "/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
[21] pry(main)> tc.site[id].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!`
[22] pry(main)> id = '/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f'
=> "/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
[23] pry(main)> tc.site[id].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!`
[24] pry(main)> id = '4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f'
=> "4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
[25] pry(main)> tc.site[id].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!`
[26] pry(main)> id = '4b30aad6-c512-4838-a328-bcd94f3cec4f'
=> "4b30aad6-c512-4838-a328-bcd94f3cec4f"
[27] pry(main)> tc.site[id].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!`
```

Note that `tc.site` is a restclient resource for connecting to a triannon running on localhost, i.e.
```ruby
tc.site
=> #<RestClient::Resource:0x007fb5b588d250
 @block=nil,
 @options={:user=>"", :password=>"", :open_timeout=>5, :read_timeout=>30},
 @url="http://localhost:3000">
```

**Comment by darrenleeweber** [comment]
Looking at the fedora repo, we have a URI for this anno at `http://localhost:8983/fedora/rest/anno/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f` and the anno data itself has a UUID of `9dd33caa-2fab-43de-9365-0a8e958c8a1e`.  However, using that UUID doesn't help, i.e.
```ruby
[29] pry(main)> tc.site['9dd33caa-2fab-43de-9365-0a8e958c8a1e'].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
[30] pry(main)> tc.site['/annotations/9dd33caa-2fab-43de-9365-0a8e958c8a1e'].delete
RestClient::ResourceNotFound: 404 Resource Not Found
from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
```

**Comment by darrenleeweber** [comment]
Blocks https://github.com/sul-dlss/triannon-client/issues/8

**Comment by darrenleeweber** [comment]
This is resolved by encoding the annotation ID, e.g.
```ruby
anno_uri = RDF::URI.new('http://your.triannon-server.com/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f')
anno_id = anno_uri.path
#=> "/annotations/4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
anno_id = anno_uri.path.split('/annotations/').last
#=> "4b/30/aa/d6/4b30aad6-c512-4838-a328-bcd94f3cec4f"
CGI::escape(anno_id)
#=> "4b%2F30%2Faa%2Fd6%2F4b30aad6-c512-4838-a328-bcd94f3cec4f"
```
