### ISSUE TITLE
Is there a docker image for Triannon?

### ISSUE THREAD

**Issue by sdellis** [sul-dlss/triannon#205]
I am a front-end developer who would like to get a local instance of Triannon running as the data store for a few Mirador annotation/transcription features I'm working on.  However, I'm running into some issues installing the whole stack on my Mac.  Not sure if it's something you've considered but a Docker image would save folks lots of time.

**Comment by sdellis** [comment]
Nevermind.  I was able to get it running with the Fedora4 docker image by @cbeer ... the only remaining question I have is whether there is a standard Triannon Solr config out there?  I noticed there was a rake task created at some point, but doesn't seem to be working...
```
$ rake triannon:solr_jetty_setup
```

**Comment by sdellis** [comment]
Ok, I found the [Solr config files](https://github.com/sul-dlss/triannon/tree/master/config/solr/triannon-core/conf) and realize I need to upgrade Solr to 4.10.4.

**Comment by darrenleeweber** [comment]
FYI, see this gist for resetting triannon
  - https://gist.github.com/darrenleeweber/bcfc9698ce5f5af8f465

**Comment by sdellis** [comment]
Thanks @darrenleeweber but I'm a little confused.  Do I need Jetty to run Triannon?  I have Tomcat/Fedora4 running in a VM and now have Solr 4.10.4 running in another VM.  Unfortunately, it doesn't like the Solr schema.xml that I pulled from this repo:
```
triannon: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: 
Could not load conf for core triannon: 
Plugin init failure for [schema.xml] fieldType "text_ws_lc": 
Plugin init failure for [schema.xml] analyzer/filter: 
Error loading class 'solr.ICUFoldingFilterFactory'. 
Schema file is /opt/solr/example/solr/triannon/conf/schema.xml
```
(I don't want to fill up your issue queue with support-related questions, so if there's a better place to ask about this stuff let me know!)

**Comment by darrenleeweber** [comment]
@sdellis - glad your trying to get it running, although bear in mind that this is pre-beta software, so we are a little on the bleeding edge here.  If you have the patience and perseverance, it can be up and running.  There are two VMs that are running this system and it might be best if our @sul-dlss/devops consider your questions.

**Comment by sdellis** [comment]
@darrenleeweber -- I'm really just trying to evaluate triannon and catch (Harvard) as annotation stores for this summer project, and blogging my experience in hopes of helping others get going.  I have patience and perseverance, but unfortunately the project I'm working on needs to be done by the end of the summer.  I need to move quickly with something that has basic functionality.  I'll repost on the IIIF list to see if anyone else outside Stanford has been able to get it to turn over with this setup.  Thanks for your help!

**Comment by sdellis** [comment]
... actually getting closer... I need to add that ICUFoldingFilterFactory to my Solr build.

**Comment by sdellis** [comment]
@darrenleeweber -- I finally got Triannon running... hooray!  Now I'm getting this when trying to create an annotation:
```
java.lang.AbstractMethodError at org.apache.solr.servlet.SolrDispatchFilter.sendError(SolrDispatchFilter.java:854) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:463) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:220) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384) URI: http://192.168.59.103:8983/solr/triannon/update?wt=ruby Request Headers: {"Content-Type"=>"text/xml"} Request Data: "foo/8c/9a/77/42/8c9a7742-89a5-4f06-88ea-a022070ca94dfoohttp://iiif.io/api/presentation/2#paintinghttp://localhost:3000/metadata/j6731452g/canvas/1external_URIcontent_as_textHello world...{\"@context\":\"http://www.w3.org/ns/oa-context-20130208.json\",\"@graph\":[{\"@id\":\"_:g2232391000\",\"@type\":\"cnt:ContentAsText\",\"chars\":\"Hello world...\",\"format\":\"text/plain\",\"language\":\"en\"},{\"@id\":\"http://localhost:3000/annotations/foo/8c/9a/77/42/8c9a7742-89a5-4f06-88ea-a022070ca94d\",\"@type\":\"oa:Annotation\",\"hasBody\":\"_:g2232391000\",\"hasTarget\":\"http://localhost:3000/metadata/j6731452g/canvas/1\",\"motivatedBy\":\"http://iiif.io/api/presentation/2#painting\"}]}" Backtrace: /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive' (eval):2:in `post' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/rsolr-1.0.12/lib/rsolr/client.rb:82:in `update' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/rsolr-1.0.12/lib/rsolr/client.rb:102:in `add' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/triannon-2.0.1/app/services/triannon/solr_writer.rb:95:in `block in add' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/retries-0.0.5/lib/retries.rb:46:in `call' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/retries-0.0.5/lib/retries.rb:46:in `with_retries' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/triannon-2.0.1/app/services/triannon/solr_writer.rb:89:in `add' /Users/shaune/.rvm/gems/ruby-2.0.0-p451/gems/triannon-2.0.1/app/services/triannon/solr_writer.rb:70:in `write'
```
Not sure what I'm doing wrong... :-/

**Comment by darrenleeweber** [comment]
@ndushay might be able to help with this.

**Comment by ndushay** [comment]
hi Shaun!

So you don't need to run Solr in jetty - it's just how it's set up for testing.  We run Solr on a completely diff box using tomcat and apache for our deployed instances of the triannon app.

I have not seen the error you have, but I'm wondering if the url need to be encoded.  I am looking into that right now -- we originally implemented triannon using a fork of Fedora that didn't use pair tree ids.  Now that was are using vanilla Fedora, the pesky slashes are perhaps an issue - I am debugging this now.

Another question is which version of java you are using.  As I recall, Fedora requires java 8 -- is your Solr instance happy?  Can you see Solr in the admin view, and can you get back empty search results on a query (assuming you have no docs in Solr).

Happy to speak w you offline if I can help.

**Comment by sdellis** [comment]
@ndushay Thanks for the tips!  Fedora seems to be happy (using the [docker image](https://registry.hub.docker.com/u/cbeer/docker-fcrepo4/) by @cbeer ).  I can see Solr in the admin view, but an empty search returns the same error, so I'm going to try to get to the bottom of that first and report back.
